In [1]:
import pandas as pd

In [80]:
df = pd.read_csv('companies_cleaned.csv')

In [4]:
df

,Unnamed: 0,Name,Location,Type,Website,Specialities,Size_least,Size_Max,Founded,Status,Followers on Stack Overflow,Link
0,0,Nord Security,Vilnius; Kaunas; Warsaw,"Cybersecurity, Network Security, Software Deve...",https://nordsecurity.com/careers,"php, go, mysql, apache-kafka, symfony, echo, c...",1000.0,5000.0,2012.0,Private,262.0,https://stackoverflow.com/jobs/companies/nord-...
1,1,Audible,Tokyo; Berlin; London,"Agile Software Development, Content Marketing,...",http://audiblecareers.com,"java, git, jquery, angular.js, requires.js, ht...",1000.0,5000.0,1995.0,Public,314.0,https://stackoverflow.com/jobs/companies/audib...
2,2,Paylocity,Praha 8; Meridian; Lake Mary,"Human Resources, Payroll, Software Development...",https://www.paylocity.com/,"aws, api-gateway, .net, c#, sql-server, react-...",5000.0,10000.0,1997.0,Public,2.0,https://stackoverflow.com/jobs/companies/paylo...
3,3,DISH,Littleton; Denver; Englewood,"Cloud Services, Information Technology, Wirele...",https://careers.dish.com,"amazon-web-services, azure, devops, f5, linux,...",10000.0,NaN,1980.0,Public,21.0,https://stackoverflow.com/jobs/companies/dish?...
4,4,Just Eat Takeaway.com,Tel Aviv-Yafo; Sofia; Berlin,"Food & Beverage, Marketplace",https://careers.justeattakeaway.com,"azure, c#, .net, javascript, react, angular, k...",10000.0,NaN,2000.0,Public,186.0,https://stackoverflow.com/jobs/companies/just-...
...,...,...,...,...,...,...,...,...,...,...,...,...
97,97,iFit,No office location,Health & Fitness,https://www.ifit.com/aboutus,"c#, objective-c, java, xamarin, git, javascrip...",201.0,500.0,1992.0,Private,340.0,https://stackoverflow.com/jobs/companies/ifit?...
98,98,Beiersdorf,Wielkopolskie; Hamburg; Ciudad de México,Beauty,https://www.beiersdorf.com/career/departments-...,"sap, sap-commerce-cloud, office365, magento, a...",10000.0,NaN,1882.0,Private,21.0,https://stackoverflow.com/jobs/companies/beier...
99,99,IT.NRW,Paderborn; Hagen; Münster,"Information Technology, Statistics",http://www.it.nrw.de/karriere,"linux, .net, abap, apache, automatisierung, an...",1000.0,5000.0,1948.0,Public,29.0,https://stackoverflow.com/jobs/companies/itnrw...
100,100,KfW,Berlin; Frankfurt am Main,"Banking, Finance",http://www.kfw.de/it-jobs,"java, pl1, javascript, python, sap, c#, c++, p...",5000.0,10000.0,1948.0,Public,8.0,https://stackoverflow.com/jobs/companies/kfw?c...
101,101,UBS,India; Hong Kong; Qatar,"Financial Services, Financial Technology",https://www.ubs.com/global/en/careers/technolo...,"javascript, java, kotlin, kubernetes, cicd, py...",10000.0,NaN,NaN,Private,5.0,https://stackoverflow.com/jobs/companies/ubs?c...

In [6]:
del df['Unnamed: 0']

In [37]:
df['Size_Average'] = df.apply(lambda x: (x.Size_least + x.Size_Max)/2 if x.Size_least != float('nan') and x.Size_Max != float('nan') else float('nan'), axis=1)
df['Size_Average'] = df['Size_Average'].apply(lambda x: str(x))
df['Size_Average'] = df['Size_Average'].apply(lambda x: float(x) if x!='nan' else float(-1))
df['Size_Average'] = df['Size_Average'].apply(lambda x: round(x) if x!=-1 else float('nan'))

In [39]:
df.columns

Index(['Name', 'Location', 'Type', 'Website', 'Specialities', 'Size_least',
       'Size_Max', 'Founded', 'Status', 'Followers on Stack Overflow', 'Link',
       'Size_Average'],
      dtype='object')

In [81]:
def remove_duplicates_comma(string):
    elements = [x.strip() for x in string.split(',')]
    unique_elements = list(set(elements))
    return ','.join(unique_elements)

def remove_duplicates_semi_column(string):
    elements = [x.strip() for x in string.split(';')]
    unique_elements = list(set(elements))
    return ';'.join(unique_elements)

df['Type'] = df['Type'].apply(remove_duplicates_comma)
df['Specialities'] = df['Specialities'].apply(remove_duplicates_comma)
df['Location'] = df['Location'].apply(remove_duplicates_semi_column)

In [82]:
def make_num(df, column, num_column, separator):
    df[num_column] = df[column].apply(lambda x: len(x.split(separator)) if x != 'nan' else 0)
    
make_num(df, 'Type', 'num_Type', ',')
make_num(df, 'Specialities', 'num_Specialities', ',')
make_num(df, 'Location', 'num_Location', ';')

In [83]:
df

,Unnamed: 0,Name,Location,Type,Website,Specialities,Size_least,Size_Max,Founded,Status,Followers on Stack Overflow,Link,num_Type,num_Specialities,num_Location
0,0,Nord Security,Warsaw;Vilnius;Kaunas,"Network Security,Cybersecurity,Software Develo...",https://nordsecurity.com/careers,"swift,jupyter,.net,next.js,reactjs,php,symfony...",1000.0,5000.0,2012.0,Private,262.0,https://stackoverflow.com/jobs/companies/nord-...,3,31,3
1,1,Audible,Tokyo;Berlin;London,"Web Technology,Content Marketing,Agile Softwar...",http://audiblecareers.com,"mason,http,perl,smoothstreaming,node,streaming...",1000.0,5000.0,1995.0,Public,314.0,https://stackoverflow.com/jobs/companies/audib...,3,44,3
2,2,Paylocity,Lake Mary;Praha 8;Meridian,"Payroll,Software Development / Engineering,Hum...",https://www.paylocity.com/,"infrastructure-as-code,swift,ruby-on-rails,nlp...",5000.0,10000.0,1997.0,Public,2.0,https://stackoverflow.com/jobs/companies/paylo...,3,32,3
3,3,DISH,Englewood;Littleton;Denver,"Wireless Communications,Information Technology...",https://careers.dish.com,"swagger,saml,azure,software-design,alm,ansible...",10000.0,NaN,1980.0,Public,21.0,https://stackoverflow.com/jobs/companies/dish?...,3,77,3
4,4,Just Eat Takeaway.com,Tel Aviv-Yafo;Berlin;Sofia,"Food & Beverage,Marketplace",https://careers.justeattakeaway.com,"c#,swift,php,angular,sql,azure,javascript,dock...",10000.0,NaN,2000.0,Public,186.0,https://stackoverflow.com/jobs/companies/just-...,2,15,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,97,iFit,No office location,Health & Fitness,https://www.ifit.com/aboutus,"c#,ios,android,objective-c,javascript,java,rea...",201.0,500.0,1992.0,Private,340.0,https://stackoverflow.com/jobs/companies/ifit?...,1,9,1
98,98,Beiersdorf,Wielkopolskie;Ciudad de México;Hamburg,Beauty,https://www.beiersdorf.com/career/departments-...,"sap-commerce-cloud,office365,azure,sap,s4hana,...",10000.0,NaN,1882.0,Private,21.0,https://stackoverflow.com/jobs/companies/beier...,1,8,3
99,99,IT.NRW,Münster;Hagen;Paderborn,"Statistics,Information Technology",http://www.it.nrw.de/karriere,"cms,.net,sap,gitlab,fur,xml,jahia,react,java,s...",1000.0,5000.0,1948.0,Public,29.0,https://stackoverflow.com/jobs/companies/itnrw...,2,55,3
100,100,KfW,Berlin;Frankfurt am Main,"Banking,Finance",http://www.kfw.de/it-jobs,"c#,php,r,c++,javascript,sap,pl1,java,python",5000.0,10000.0,1948.0,Public,8.0,https://stackoverflow.com/jobs/companies/kfw?c...,2,9,2
101,101,UBS,Qatar;India;Hong Kong,"Financial Services,Financial Technology",https://www.ubs.com/global/en/careers/technolo...,"swift,azure,gitlab,reactjs,java,maven,postgres...",10000.0,NaN,NaN,Private,5.0,https://stackoverflow.com/jobs/companies/ubs?c...,2,27,3

In [84]:
types = pd.Series([])
specialities = pd.Series([])
locations = pd.Series([])
def series(series_name, column, num_column, separator):
    for i in range(0, len(df)):
        for j in range(0, int(df[num_column][i])):
            item = df[column][i].split(separator)[j]
            series_name.loc[len(series_name)] = str(item)   
            
series(types, 'Type', 'num_Type', ',')
series(specialities, 'Specialities', 'num_Specialities', ',')
series(locations, 'Location', 'num_Location', ';')

In [85]:
types.value_counts()

Information Technology                18
Financial Technology                  15
Software Development / Engineering    10
Financial Services                     9
Software Development                   9
                                      ..
Science                                1
Internet Marketing                     1
Business Process Outsourcing           1
System Integration                     1
Statistics                             1
Name: count, Length: 110, dtype: int64

In [86]:
specialities.value_counts()

java                  76
javascript            73
python                62
c#                    55
kubernetes            55
                      ..
confluent-platform     1
aspose                 1
rackspace              1
nuget                  1
nist                   1
Name: count, Length: 878, dtype: int64

In [87]:
locations.value_counts()

Berlin       14
Bengaluru    11
London        8
New York      7
Singapore     5
             ..
Quận 1        1
Kroměříž      1
Tân Bình      1
Veghel        1
Hong Kong     1
Name: count, Length: 172, dtype: int64

In [88]:
df.to_csv('companies_cleaned_1.csv')

In [89]:
types.to_csv('types.csv')

In [90]:
specialities.to_csv('specialities.csv')

In [91]:
locations.to_csv('locations.csv')